name: Maven Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        java: [8, 11, 17, 21]

    name: Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - run: java -version && mvn --version
    - run: mvn --activate-profiles dist --no-transfer-progress package
    - uses: actions/upload-artifact@v3
      with:
        name: BungeeCord
        path: bootstrap/target/BungeeCord.jar
